import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Appbar from "@/components/Appbar";

const sans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-auto hide-scrollbar">
      <body className={sans.className}>
        <div className=" bg-white">
          <Appbar />
          {children}
        </div>
      </body>
    </html>
  );
}
